name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: |
          if [ ${{ steps.build.outcome }} == 'success' ]; then
            echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
            npm publish --access public
          else
            echo "Tests failed. Skipping npm publish."
          fi
